name: Build  Docker image 

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Start the workflow
        run: echo "Hii"

      - uses: actions/checkout@v3

      - name: Build the docker image 
        run: docker build -t myapp ./L01

      - name: Run the Docker contsiner 
        run: docker run -d -p 3000:3000 --name myapp myapp

      - name: Wait for app startup
        run: sleep 5

      - name: Test App
        run: curl http://localhost:3000
      
    